"""Marker-based PDF -> Markdown conversion helpers.

Supported conversion types:
1) arxiv -> standard Marker conversion, best for born-digital papers.
2) ocr   -> Marker conversion with force_ocr enabled for scanned PDFs.
"""

from __future__ import annotations

import importlib.util
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


@dataclass
class ConversionBundle:
    markdown_text: str
    provider: str
    scanned: bool
    output_dir: Optional[Path] = None
    assets_dir: Optional[Path] = None


def _module_available(name: str) -> bool:
    return importlib.util.find_spec(name) is not None


def _command_available(name: str) -> bool:
    return shutil.which(name) is not None


def clean_text_for_markdown(text: str) -> str:
    normalized = (text or "").replace("\r\n", "\n").replace("\r", "\n")
    normalized = normalized.strip()
    if not normalized:
        return ""
    lines = [line.rstrip() for line in normalized.split("\n")]
    collapsed: list[str] = []
    blank_run = 0
    for line in lines:
        if line.strip():
            blank_run = 0
            collapsed.append(line)
            continue
        blank_run += 1
        if blank_run <= 2:
            collapsed.append("")
    result = "\n".join(collapsed).strip()
    return (result + "\n") if result else ""


def _run_command(cmd: list[str], cwd: Optional[Path] = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        capture_output=True,
        text=True,
        check=False,
    )


def _read_best_markdown_file(output_dir: Path) -> str:
    candidates = list(output_dir.rglob("output.md"))
    if not candidates:
        candidates = list(output_dir.rglob("*.md"))
    if not candidates:
        raise RuntimeError("No markdown file was generated by Marker.")
    candidates.sort(key=lambda path: (len(path.parts), path.name))
    return candidates[0].read_text(encoding="utf-8", errors="replace")


def _guess_assets_dir(output_dir: Path) -> Optional[Path]:
    image_dirs: list[Path] = []
    for candidate in output_dir.rglob("*"):
        if not candidate.is_dir():
            continue
        try:
            has_images = any(child.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp"} for child in candidate.iterdir())
        except OSError:
            has_images = False
        if has_images:
            image_dirs.append(candidate)
    if not image_dirs:
        return None
    image_dirs.sort(key=lambda path: (len(path.parts), path.name))
    return image_dirs[0]


def _run_marker_cli(pdf_path: Path, output_dir: Path, *, force_ocr: bool) -> ConversionBundle:
    cmd = [
        "marker_single",
        str(pdf_path),
        "--output_dir",
        str(output_dir),
        "--output_format",
        "markdown",
        "--disable_multiprocessing",
        "--disable_tqdm",
    ]
    if force_ocr:
        cmd.append("--force_ocr")
    completed = _run_command(cmd)
    if completed.returncode != 0:
        stderr = (completed.stderr or completed.stdout or "").strip()
        raise RuntimeError(f"Marker failed: {stderr}")
    return ConversionBundle(
        markdown_text=clean_text_for_markdown(_read_best_markdown_file(output_dir)),
        provider="marker-ocr" if force_ocr else "marker-arxiv",
        scanned=force_ocr,
        output_dir=output_dir,
        assets_dir=_guess_assets_dir(output_dir),
    )


def _run_marker_module(pdf_path: Path, output_dir: Path, *, force_ocr: bool) -> ConversionBundle:
    from marker.converters.pdf import PdfConverter  # type: ignore
    from marker.models import create_model_dict  # type: ignore
    from marker.output import text_from_rendered  # type: ignore

    output_dir.mkdir(parents=True, exist_ok=True)
    converter_kwargs = {"artifact_dict": create_model_dict()}
    if force_ocr:
        converter_kwargs["config"] = {"force_ocr": True}
    converter = PdfConverter(**converter_kwargs)
    rendered = converter(str(pdf_path))
    text, _, images = text_from_rendered(rendered)
    assets_dir = None
    if images:
        assets_dir = output_dir / "images"
        assets_dir.mkdir(parents=True, exist_ok=True)
        for image_name, image in images.items():
            image_path = assets_dir / image_name
            image.save(image_path)
    return ConversionBundle(
        markdown_text=clean_text_for_markdown(text),
        provider="marker-ocr" if force_ocr else "marker-arxiv",
        scanned=force_ocr,
        output_dir=output_dir,
        assets_dir=assets_dir,
    )


def _run_marker(pdf_path: Path, output_dir: Path, *, force_ocr: bool) -> ConversionBundle:
    output_dir.mkdir(parents=True, exist_ok=True)
    if _command_available("marker_single"):
        return _run_marker_cli(pdf_path, output_dir, force_ocr=force_ocr)
    if _module_available("marker.converters.pdf"):
        return _run_marker_module(pdf_path, output_dir, force_ocr=force_ocr)
    raise RuntimeError("Marker is not installed.")


def convert_pdf_to_markdown_bundle(
    pdf_path: Path,
    output_dir: Optional[Path] = None,
    conversion_type: str = "arxiv",
    force_mode: str = "auto",
    ocr_lang: str = "eng",
) -> ConversionBundle:
    del force_mode
    del ocr_lang

    mode = (conversion_type or "arxiv").strip().lower()
    if mode not in {"arxiv", "ocr"}:
        raise ValueError("conversion_type must be one of: arxiv, ocr")
    if not pdf_path.exists() or not pdf_path.is_file():
        raise FileNotFoundError(f"PDF not found: {pdf_path}")

    work_dir = output_dir or pdf_path.parent / f"{pdf_path.stem}_artifacts"
    work_dir.mkdir(parents=True, exist_ok=True)
    return _run_marker(pdf_path, work_dir / "marker", force_ocr=(mode == "ocr"))


def convert_pdf_to_markdown(
    pdf_path: Path,
    conversion_type: str = "arxiv",
    force_mode: str = "auto",
    ocr_lang: str = "eng",
) -> str:
    return convert_pdf_to_markdown_bundle(
        pdf_path=pdf_path,
        output_dir=None,
        conversion_type=conversion_type,
        force_mode=force_mode,
        ocr_lang=ocr_lang,
    ).markdown_text
